/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v6.0
processor: MKV31F512xxx12
package_id: MKV31F512VLL12
mcu_data: ksdk2_0
processor_version: 6.0.1
pin_labels:
- {pin_num: '80', pin_signal: ADC1_SE4b/CMP0_IN2/PTC8/FTM3_CH4/FB_AD7, label: VH, identifier: VH}
- {pin_num: '81', pin_signal: ADC1_SE5b/CMP0_IN3/PTC9/FTM3_CH5/FB_AD6/FTM2_FLT0, label: VL, identifier: VL}
- {pin_num: '82', pin_signal: ADC1_SE6b/PTC10/I2C1_SCL/FTM3_CH6/FB_AD5, label: WH, identifier: WH}
- {pin_num: '83', pin_signal: ADC1_SE7b/PTC11/LLWU_P11/I2C1_SDA/FTM3_CH7/FB_RW_b, label: WL, identifier: WL}
- {pin_num: '93', pin_signal: PTD0/LLWU_P12/SPI0_PCS0/UART2_RTS_b/FTM3_CH0/FB_ALE/FB_CS1_b/FB_TS_b/LPUART0_RTS_b, label: UH, identifier: UH}
- {pin_num: '94', pin_signal: ADC0_SE5b/PTD1/SPI0_SCK/UART2_CTS_b/FTM3_CH1/FB_CS0_b/LPUART0_CTS_b, label: UL, identifier: UL}
- {pin_num: '42', pin_signal: PTA12/FTM1_CH0/FTM1_QD_PHA, label: BST_CHNL_0, identifier: BST_CHNL_0}
- {pin_num: '43', pin_signal: PTA13/LLWU_P4/FTM1_CH1/FTM1_QD_PHB, label: BST_CHNL_1, identifier: BST_CHNL_1}
- {pin_num: '76', pin_signal: PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/FTM0_CH3/FB_AD11/CMP1_OUT/LPUART0_TX, label: Fault_PS, identifier: Fault_INV;FLT_INV}
- {pin_num: '70', pin_signal: ADC0_SE14/PTC0/SPI0_PCS4/PDB0_EXTRG/FB_AD14/FTM0_FLT1/SPI0_PCS0, label: FAULT_AC_BST, identifier: FLT_BST}
- {pin_num: '14', pin_signal: ADC0_DP1, label: I_PV_p, identifier: I_PV_p}
- {pin_num: '15', pin_signal: ADC0_DM1, label: I_PV_n, identifier: I_PV_n}
- {pin_num: '18', pin_signal: ADC0_DP0/ADC1_DP3, label: V_DC_p, identifier: V_DC_;V_DC_p}
- {pin_num: '19', pin_signal: ADC0_DM0/ADC1_DM3, label: V_DC_n, identifier: V_DC_n}
- {pin_num: '20', pin_signal: ADC1_DP0/ADC0_DP3, label: V_PV_p, identifier: V_PV_p}
- {pin_num: '21', pin_signal: ADC1_DM0/ADC0_DM3, label: V_PV_n, identifier: V_PV_n}
- {pin_num: '16', pin_signal: ADC1_DP1/ADC0_DP2, label: I_INV_n, identifier: I_INV_n}
- {pin_num: '28', pin_signal: DAC1_OUT/CMP0_IN4/ADC1_SE23, label: I_INV_u, identifier: I_INV_u}
- {pin_num: '26', pin_signal: VREF_OUT/CMP1_IN5/CMP0_IN5/ADC1_SE18, label: I_INV_w, identifier: I_INV_w}
- {pin_num: '27', pin_signal: DAC0_OUT/CMP1_IN3/ADC0_SE23, label: I_INV_v, identifier: I_INV_V;I_INV_v}
- {pin_num: '6', pin_signal: PTE5/SPI1_PCS2/LPUART0_RX/FTM3_CH0, label: test, identifier: test}
- {pin_num: '64', pin_signal: PTB18/FTM2_CH0/FB_AD15/FTM2_QD_PHA, label: AC_BST_1, identifier: AC_BST_1}
- {pin_num: '65', pin_signal: PTB19/FTM2_CH1/FB_OE_b/FTM2_QD_PHB, label: AC_BST_2, identifier: AC_BST_2}
- {pin_num: '55', pin_signal: ADC0_SE12/PTB2/I2C0_SCL/UART0_RTS_b/FTM0_FLT1/FTM0_FLT3, label: relay, identifier: relay;relay_rect}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '93', peripheral: FTM3, signal: 'CH, 0', pin_signal: PTD0/LLWU_P12/SPI0_PCS0/UART2_RTS_b/FTM3_CH0/FB_ALE/FB_CS1_b/FB_TS_b/LPUART0_RTS_b, direction: OUTPUT}
  - {pin_num: '94', peripheral: FTM3, signal: 'CH, 1', pin_signal: ADC0_SE5b/PTD1/SPI0_SCK/UART2_CTS_b/FTM3_CH1/FB_CS0_b/LPUART0_CTS_b, direction: OUTPUT}
  - {pin_num: '80', peripheral: FTM3, signal: 'CH, 4', pin_signal: ADC1_SE4b/CMP0_IN2/PTC8/FTM3_CH4/FB_AD7, direction: OUTPUT}
  - {pin_num: '81', peripheral: FTM3, signal: 'CH, 5', pin_signal: ADC1_SE5b/CMP0_IN3/PTC9/FTM3_CH5/FB_AD6/FTM2_FLT0, direction: OUTPUT}
  - {pin_num: '82', peripheral: FTM3, signal: 'CH, 6', pin_signal: ADC1_SE6b/PTC10/I2C1_SCL/FTM3_CH6/FB_AD5, direction: OUTPUT}
  - {pin_num: '83', peripheral: FTM3, signal: 'CH, 7', pin_signal: ADC1_SE7b/PTC11/LLWU_P11/I2C1_SDA/FTM3_CH7/FB_RW_b, direction: OUTPUT}
  - {pin_num: '42', peripheral: FTM1, signal: 'CH, 0', pin_signal: PTA12/FTM1_CH0/FTM1_QD_PHA, direction: OUTPUT}
  - {pin_num: '43', peripheral: FTM1, signal: 'CH, 1', pin_signal: PTA13/LLWU_P4/FTM1_CH1/FTM1_QD_PHB, direction: OUTPUT}
  - {pin_num: '14', peripheral: ADC0, signal: 'DP, 1', pin_signal: ADC0_DP1}
  - {pin_num: '15', peripheral: ADC0, signal: 'DM, 1', pin_signal: ADC0_DM1}
  - {pin_num: '16', peripheral: ADC0, signal: 'SE, 2', pin_signal: ADC1_DP1/ADC0_DP2}
  - {pin_num: '28', peripheral: ADC1, signal: 'SE, 23', pin_signal: DAC1_OUT/CMP0_IN4/ADC1_SE23}
  - {pin_num: '26', peripheral: ADC1, signal: 'SE, 18', pin_signal: VREF_OUT/CMP1_IN5/CMP0_IN5/ADC1_SE18}
  - {pin_num: '27', peripheral: ADC0, signal: 'SE, 23', pin_signal: DAC0_OUT/CMP1_IN3/ADC0_SE23, identifier: I_INV_v}
  - {pin_num: '76', peripheral: GPIOC, signal: 'GPIO, 4', pin_signal: PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/FTM0_CH3/FB_AD11/CMP1_OUT/LPUART0_TX, identifier: FLT_INV, direction: INPUT}
  - {pin_num: '70', peripheral: GPIOC, signal: 'GPIO, 0', pin_signal: ADC0_SE14/PTC0/SPI0_PCS4/PDB0_EXTRG/FB_AD14/FTM0_FLT1/SPI0_PCS0, direction: INPUT}
  - {pin_num: '18', peripheral: ADC1, signal: 'DP, 3', pin_signal: ADC0_DP0/ADC1_DP3, identifier: V_DC_p}
  - {pin_num: '19', peripheral: ADC1, signal: 'DM, 3', pin_signal: ADC0_DM0/ADC1_DM3}
  - {pin_num: '20', peripheral: ADC1, signal: 'DP, 0', pin_signal: ADC1_DP0/ADC0_DP3}
  - {pin_num: '21', peripheral: ADC1, signal: 'DM, 0', pin_signal: ADC1_DM0/ADC0_DM3}
  - {pin_num: '6', peripheral: GPIOE, signal: 'GPIO, 5', pin_signal: PTE5/SPI1_PCS2/LPUART0_RX/FTM3_CH0, direction: OUTPUT}
  - {pin_num: '64', peripheral: FTM2, signal: 'CH, 0', pin_signal: PTB18/FTM2_CH0/FB_AD15/FTM2_QD_PHA, direction: OUTPUT}
  - {pin_num: '65', peripheral: FTM2, signal: 'CH, 1', pin_signal: PTB19/FTM2_CH1/FB_OE_b/FTM2_QD_PHB, direction: OUTPUT}
  - {pin_num: '55', peripheral: GPIOB, signal: 'GPIO, 2', pin_signal: ADC0_SE12/PTB2/I2C0_SCL/UART0_RTS_b/FTM0_FLT1/FTM0_FLT3, identifier: relay_rect, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    gpio_pin_config_t relay_rect_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB2 (pin 55)  */
    GPIO_PinInit(BOARD_INITPINS_relay_rect_GPIO, BOARD_INITPINS_relay_rect_PIN, &relay_rect_config);

    gpio_pin_config_t FLT_BST_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC0 (pin 70)  */
    GPIO_PinInit(BOARD_INITPINS_FLT_BST_GPIO, BOARD_INITPINS_FLT_BST_PIN, &FLT_BST_config);

    gpio_pin_config_t FLT_INV_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC4 (pin 76)  */
    GPIO_PinInit(BOARD_INITPINS_FLT_INV_GPIO, BOARD_INITPINS_FLT_INV_PIN, &FLT_INV_config);

    gpio_pin_config_t test_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE5 (pin 6)  */
    GPIO_PinInit(BOARD_INITPINS_test_GPIO, BOARD_INITPINS_test_PIN, &test_config);

    /* PORTA12 (pin 42) is configured as FTM1_CH0 */
    PORT_SetPinMux(BOARD_INITPINS_BST_CHNL_0_PORT, BOARD_INITPINS_BST_CHNL_0_PIN, kPORT_MuxAlt3);

    /* PORTA13 (pin 43) is configured as FTM1_CH1 */
    PORT_SetPinMux(BOARD_INITPINS_BST_CHNL_1_PORT, BOARD_INITPINS_BST_CHNL_1_PIN, kPORT_MuxAlt3);

    /* PORTB18 (pin 64) is configured as FTM2_CH0 */
    PORT_SetPinMux(BOARD_INITPINS_AC_BST_1_PORT, BOARD_INITPINS_AC_BST_1_PIN, kPORT_MuxAlt3);

    /* PORTB19 (pin 65) is configured as FTM2_CH1 */
    PORT_SetPinMux(BOARD_INITPINS_AC_BST_2_PORT, BOARD_INITPINS_AC_BST_2_PIN, kPORT_MuxAlt3);

    /* PORTB2 (pin 55) is configured as PTB2 */
    PORT_SetPinMux(BOARD_INITPINS_relay_rect_PORT, BOARD_INITPINS_relay_rect_PIN, kPORT_MuxAsGpio);

    /* PORTC0 (pin 70) is configured as PTC0 */
    PORT_SetPinMux(BOARD_INITPINS_FLT_BST_PORT, BOARD_INITPINS_FLT_BST_PIN, kPORT_MuxAsGpio);

    /* PORTC10 (pin 82) is configured as FTM3_CH6 */
    PORT_SetPinMux(BOARD_INITPINS_WH_PORT, BOARD_INITPINS_WH_PIN, kPORT_MuxAlt3);

    /* PORTC11 (pin 83) is configured as FTM3_CH7 */
    PORT_SetPinMux(BOARD_INITPINS_WL_PORT, BOARD_INITPINS_WL_PIN, kPORT_MuxAlt3);

    /* PORTC4 (pin 76) is configured as PTC4 */
    PORT_SetPinMux(BOARD_INITPINS_FLT_INV_PORT, BOARD_INITPINS_FLT_INV_PIN, kPORT_MuxAsGpio);

    /* PORTC8 (pin 80) is configured as FTM3_CH4 */
    PORT_SetPinMux(BOARD_INITPINS_VH_PORT, BOARD_INITPINS_VH_PIN, kPORT_MuxAlt3);

    /* PORTC9 (pin 81) is configured as FTM3_CH5 */
    PORT_SetPinMux(BOARD_INITPINS_VL_PORT, BOARD_INITPINS_VL_PIN, kPORT_MuxAlt3);

    /* PORTD0 (pin 93) is configured as FTM3_CH0 */
    PORT_SetPinMux(BOARD_INITPINS_UH_PORT, BOARD_INITPINS_UH_PIN, kPORT_MuxAlt4);

    /* PORTD1 (pin 94) is configured as FTM3_CH1 */
    PORT_SetPinMux(BOARD_INITPINS_UL_PORT, BOARD_INITPINS_UL_PIN, kPORT_MuxAlt4);

    /* PORTE5 (pin 6) is configured as PTE5 */
    PORT_SetPinMux(BOARD_INITPINS_test_PORT, BOARD_INITPINS_test_PIN, kPORT_MuxAsGpio);

    SIM->SOPT4 = ((SIM->SOPT4 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT4_FTM1CH0SRC_MASK | SIM_SOPT4_FTM2CH0SRC_MASK | SIM_SOPT4_FTM2CH1SRC_MASK)))

                  /* FTM1 channel 0 input capture source select: FTM1_CH0 signal. */
                  | SIM_SOPT4_FTM1CH0SRC(SOPT4_FTM1CH0SRC_FTM)

                  /* FTM2 channel 0 input capture source select: FTM2_CH0 signal. */
                  | SIM_SOPT4_FTM2CH0SRC(SOPT4_FTM2CH0SRC_FTM)

                  /* FTM2 channel 1 input capture source select: FTM2_CH1 signal. */
                  | SIM_SOPT4_FTM2CH1SRC(SOPT4_FTM2CH1SRC_FTM));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
